//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtmApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionsId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> TransactionTime { get; set; }
        public string TransactionLocation { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> CardType { get; set; }
        public Nullable<int> CardID { get; set; }
        public string Amount { get; set; }
    
        public virtual Card Card { get; set; }
    }
}
