//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtmApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UsersId { get; set; }
        public string FirstName_ { get; set; }
        public string LastName { get; set; }
        public string TelephoneNumber { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public Nullable<int> CustomerNumber { get; set; }
        public Nullable<int> Pin { get; set; }
        public Nullable<int> CardID { get; set; }
    
        public virtual Card Card { get; set; }
    }
}
